### ISSUE TITLE
Need a lighter version 

### ISSUE THREAD

**Issue by atashi764** [Rinloid/musk_rose_rd#3]
hello there, the shader is really good. the colors feel so vibrant but i own a really bad pc which lags horribly when looking at water or sky. it would be nice if you bring a light version.

or is it possible to remove sky by not using sky....bin?

**Comment by Rinloid** [comment]
Adding a lighter version is planned.  And you can easily revert the sky by removing cubemap textures in the base resource pack.

**Comment by Rinloid** [comment]
Added a lighter version.  Closing.
