### ISSUE TITLE
better moon.

### ISSUE THREAD

**Issue by hirun37440** [Rinloid/musk_rose_rd#4]
.hey. can you make the moon better in Musk rose_rd v4.0? and why do the clouds disappear when it turns nighttime? and the CAVES are ULTRA ddark. i cant see anythinggggg. its like a blackhole

**Comment by Rinloid** [comment]
> can you make the moon better

The game doesn't tell us which moon phase the moon is so we consider the moon is always full in the shader.
>why do the clouds disappear when it turns nighttime?

It doesn't disappear.  The sky at night is just too dark to see the clouds.
>the CAVES are ULTRA ddark. i cant see anythinggggg. its like a blackhole

It's as dark as vanilla.

**Comment by hirun37440** [comment]
hey. its me again. if you can please make an 80% or 60% brightness musk rose shader if you can. pleaseee. and when I use night vision potion it does not work while I use the shader also....
