### ISSUE TITLE
Lite

### ISSUE THREAD

**Issue by Galoredust** [Rinloid/musk_rose_rd#5]
When using this shader everything is good until you look at the water or sky pls make a lite version without water reflection, godrays or moving clouds and pls use fluffy cubic clouds

**Comment by Rinloid** [comment]
>When using this shader everything is good until you look at the water or sky pls make a lite version without water reflection

Dupe of #3.
>godrays

Impossible right now, and it's laggy.
>moving clouds

They are already moving!
>pls use fluffy cubic clouds

It's not my favourite.
