### ISSUE TITLE
洞窟内が少し暗いです。

### ISSUE THREAD

**Issue by minotto165** [Rinloid/musk_rose_rd#6]
アップデート待ってました！
しかし、光が入っていないところは少し暗く、見にくいです。
前は洞窟内でもかなり見やすかったと思います。
洞窟でも見やすいように、もう少し明るくできないでしょうか。

**Comment by Rinloid** [comment]
シェーダーを適用していない状態と同じ明るさになるように調整したので、それよりも明るくしたり暗くしたりする予定はありません。ご了承ください。

**Comment by minotto165** [comment]
![image](https://github.com/Rinloid/musk_rose_rd/assets/109657703/a3a66086-afe6-4e7b-9ba7-4082a2275dec)
何度もすみません、ですがちょっと暗いと思いませんか？
最低の明度をもう少し上げられないでしょうか。
何度もすみません。

**Comment by Rinloid** [comment]
比較用の画像を用意しました。左がデフォルト（明るさ 50）です。
![Minecraft 03_06_2023 17_10_20](https://github.com/Rinloid/musk_rose_rd/assets/81559497/25f36b1d-0264-4ade-b403-6ff1b1617968)
普段明るさ 50 より上でプレイしていて、それに慣れているのなら申し訳ありません。しかしながら、本来光が無い場所は何も見えないほど暗い状態であるべきなのですが、ゲームの光源は現実世界のものよりもずっと簡素で、普通に光の計算を行っていると光が無い場所が多くなり、不自然になってしまいます。なのでデフォルトと同じ明るさにしました。

**Comment by minotto165** [comment]
なるほど！
丁寧な説明ありがとうございました。
