### ISSUE TITLE
Make a bright version of musk rose shader.

### ISSUE THREAD

**Issue by hirun37440** [Rinloid/musk_rose_rd#8]
hey. its me again. if you can please make an 80% or 60% brightness musk rose shader if you can. pleaseee. and when I use night vision potion it does not work while I use the shader also....

_Originally posted by @hirun1228 in https://github.com/Rinloid/musk_rose_rd/issues/4#issuecomment-1589902251_

**Comment by Rinloid** [comment]
I won't.  I'm _really_ comfortable with the current brightness.  Night vision also is not supported since the shader don't use the vanilla lightmap sampler.

**Comment by hirun37440** [comment]
😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭
