### ISSUE TITLE
very resource heavy

### ISSUE THREAD

**Issue by atashi764** [Rinloid/musk_rose_rd#9]
hello there, thanks for bringing lite version.

but the lite version give unplayable experience especially when looking at ground. also clouds don't render. not sure if it's a bug or feature. 

my request is to make the lite version more lighter so entry level devices get a playable experience. thanks in advance 🍡

**Comment by Rinloid** [comment]
I tried optimizing the shader as possible as I can by removing clouds and water waves but the atmosphere scattering causes a lag so much.  I don't recommend to play it on mobile phones.
